site_name: F1 Data Wiki
theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/josh-sandrone-059b97195/

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
