name: ci
on:
  push:
    branches:
      - live

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - run: pip install -r requirements.txt
      - run: find . -name "*.md" -exec iconv -f utf-8 -t utf-8 {} \; -exec echo "Checked {}" \;
      - run: mkdocs gh-deploy --force
